### ISSUE TITLE
csslint.net breaks on a css rule

### ISSUE THREAD

**Issue by 3rd-Eden** [CSSLint/csslint#179]
Hello,

When I go to the site and validate my co-worker's CSS it throws a JavaScript exception:

``` log
Uncaught TypeError: Cannot read property 'name' of undefined csslint-ui.js:158 ( tr.cells[3].innerHTML = htmlEscape(messages[i].rule.name);)
```

I have managed to narrow it down to one single rule

``` css
.top h1 a { background: url(../images/background/logo.png) no-repeat; display: block; height: 44px; position: relative; text-indent: -9999px; width: 250px; }
```

If I remove the `display:block` it works just fine.
