### ISSUE TITLE
keyframes and duplicate-properties

### ISSUE THREAD

**Issue by joestelmach** [CSSLint/csslint#202]
The following css results in a **Duplicate property 'bottom' found** warning when the **'duplicate-properties'** option is enabled.

``` css
@-webkit-keyframes slide_up {
  from {  
    bottom:-91px;
  }  

  to {  
    bottom:0;
  } 
}
```
