### ISSUE TITLE
Unqualified attribute selector warning with input[type="text"] 

### ISSUE THREAD

**Issue by johnkhughes** [CSSLint/csslint#239]
The following CSS produces an "unqualified attribute selector" warning, even though the selector is qualified:

``` css
input[type="text"] {
    color: red;
}
```
