### ISSUE TITLE
Rule Proposal: Always use :focus when using :hover

### ISSUE THREAD

**Issue by nzakas** [CSSLint/csslint#264]
For accessibility purposes, it's usually advisable to include a rule for :focus whenever there's something for :hover. So

``` css
a:hover,
a:focus {
    color:red;
}
```
