### ISSUE TITLE
calc() causing RBRACE Expected error

### ISSUE THREAD

**Issue by constantology** [CSSLint/csslint#267]
Hi, 

we use CSSLint at work and I broke the build with code similar to: 

``` css

.selector {
    border   : 1px solid #ccc ; 
    padding  : 4px 8px 3px ; 
    width    : 99% ; 
        width : -moz-calc( 100% - 16px ) ; 
        width : -webkit-calc( 100% - 16px ) ; 
    width    : calc( 100% - 16px ) ; 
    }

```

The error we get is something like, `RBRACE Expected at line X....`

This has happened when `calc()` is used for heights and widths. I've noticed that there is no support for calc in CSSLint right now, is there a plan to add it any time soon?
