### ISSUE TITLE
Disallow unqualified attribute selectors: is class disregarded?

### ISSUE THREAD

**Issue by gurdiga** [CSSLint/csslint#318]
Is that OK that this rule triggers the “Unqualified attribute selectors are known to be slow.” warning?
```css
.buton[data-formular] {
  display: inline-block;
  vertical-align: -3px;
  border: none;
  background-color: transparent;
  text-indent: 0;
  cursor: pointer;
}
```
I mean is it OK that the class here is disregarded?
