### ISSUE TITLE
@media { @page{} } throws error.

### ISSUE THREAD

**Issue by roelven** [CSSLint/csslint#49]
in html5boilerplate style.css:

``` css
 @page { margin: 0.5cm; }
```

throws an error while this is syntactically an edge case, it's correct to define the [page-box](http://www.w3.org/TR/CSS2/page.html#page-box).
