### ISSUE TITLE
Error due to keyframe animation

### ISSUE THREAD

**Issue by lukasoppermann** [CSSLint/csslint#510]
A keyframe animation like this produces many errors like:

```
Unexpected token '{' at line 77, col 5. 
This rule looks for recoverable syntax errors. (errors)
```

Can you add an option to allow animations or make it not break on this?

``` css
@-webkit-keyframes fadeBlue{
    0%{
        background-color: rgba(55,115,215,0.75);
    }
    100{
        background-color: rgba(55,115,215,1);
    }
}
```
