### ISSUE TITLE
Rule is empty when defining root-only CSS variables

### ISSUE THREAD

**Issue by eliperelman** [CSSLint/csslint#538]
When using csslint with variables against the `:root` element, it throws the message of "rule is empty".

``` css
:root {
  --color-alpha: #fff;
}
```

This rule should not be considered empty against the `:root` element that only contains CSS variables as it is considered the de-facto way to create them globally.
