### ISSUE TITLE
False positive on @ rule: @-o-viewport

### ISSUE THREAD

**Issue by kweij** [CSSLint/csslint#561]
The following code:
```css
@-o-viewport {
    width: device-width;
}
```
will unexpectedly raise the following error: `Unknown @ rule: @-o-viewport`

This @ rule is however valid and should not raise an error.
