### ISSUE TITLE
vendor prefixes bug

### ISSUE THREAD

**Issue by lifeiscontent** [CSSLint/csslint#579]
``` css
input[type="search"]::-webkit-search-cancel-button,
input[type="search"]::-webkit-search-decoration { -webkit-appearance: none; }
```

this css line makes this warning trigger.

``` bash
WARNING: The property -moz-appearance is compatible with -webkit-appearance and should be included as well. Include all compatible vendor prefixes to reach a wider range of users. (compatible-vendor-prefixes) Browsers: All
```

css lint should be smarter
