### ISSUE TITLE
Unexpected token '\0' 

### ISSUE THREAD

**Issue by alundiak** [CSSLint/csslint#604]
Indeed this is CSS hack, but I need in my code:

```css
.dropdown .text-field .ghost {
  margin-top: -2px;
  margin-top: -3px\0; /*For IE*/
}
```

And csslint tells me:

```
Unexpected token '3px\0' at line ...
  margin-top: -3px\0;
```
Similar answer tells me `grunt-contrib-csslint`.

Is this a designed behavior?
