### ISSUE TITLE
Missing semicolon not linting in css

### ISSUE THREAD

**Issue by Srcky** [CSSLint/csslint#617]
When there is only one property for a certain selector, and it's missing a semicolon, CSSLint won't show it as error. For instance:
```css
a {
color: #0083e8
}
```
This won't show as error.
