### ISSUE TITLE
border-image-repeat: Expected (stretch | repeat | round) but found 'initial'.

### ISSUE THREAD

**Issue by jonathanlinat** [CSSLint/csslint#718]
CSS:

```css
.parent input {
    border-image-repeat: initial;
}
```

Error:

```bash
Expected (stretch | repeat | round) but found 'initial'.
    border-image-repeat: initial;
```

`initial`, as reported by [MDN web doc](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-repeat#wikiArticle), is a **valid global value** of the CSS3 `border-image-repeat` property and shouldn't be considered as invalid by CSSLint.

CSSLint version: v1.0.4
