### ISSUE TITLE
Fatal error: margin in keyframes

### ISSUE THREAD

**Issue by toptalo** [CSSLint/csslint#747]
Using margins in animations is a bad idea, but this lines:

```css
@keyframes example {
  0% {
    margin-left: 100px;
  }
  100% {
    margin-left: 0;
  }
}
```

returns:

```
[Lundefined:Cundefined]
>> ERROR: Fatal error, cannot continue: Cannot set property 'margin-left' of undefined undefined (undefined) Browsers: undefined
```
